version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["/TFR/Dockerfile"]

[[transformers]]
name = "black"