version: "3.9"

services:
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      DOMAIN: expo.leggy.dev
    links:
      - highscore

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
      POSTGRES_PORT: 5432
    links:
      - highscore

  highscore:
    build: ./Highscore-Server
    volumes:
      - ./Highscore-Server/data:/data/storage
      - ./Highscore-Server/logs:/data/logs
      # Pass in the code to the container so I don't
      # have to rebuild it every time during development
      - ./Highscore-Server/highscore:/data/highscore
    environment:
      FLASK_KEY: secret
      BEARER_TOKEN: 1234
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: database
