version: "3.9"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      THE_FRONT_ROOMS_DOMAIN: ${THE_FRONT_ROOMS_DOMAIN}
      GAME_EXPO_DOMAIN: ${GAME_EXPO_DOMAIN}
    links:
      - tfr
      - expo

  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    links:
      - tfr

  tfr:
    build: TFR
    restart: unless-stopped
    volumes:
      - ./TFR/storage:/data/storage
      - ./TFR/logs:/data/logs
    environment:
      FLASK_KEY: ${THE_FRONT_ROOMS_SECRETE_KEY}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}

  expo:
    build: GameExpo
    restart: unless-stopped
    volumes:
      - ./GameExpo/storage:/data/storage
      - ./GameExpo/logs:/data/logs
    environment:
      FLASK_KEY: ${GAME_EXPO_SECRETE_KEY}
