version: "3.9"

services:
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      - ACME_AGREE=true
      - DOMAIN=expo.leggy.dev
    links:
      - highscore

  highscore:
    build: ./Highscore-Server
    volumes:
      - ./Highscore-Server/data:/data/storage
    environment:
      - FLASK_KEY=secret
      - BEARER_TOKEN=1234
