version: "3.9"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      THE_FRONT_ROOMS_DOMAIN: ${THE_FRONT_ROOMS_DOMAIN}
    links:
      - tfr

  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
      - /var/log/postgresql:/var/log/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c log_connections=on -c log_line_prefix='%m {%h} [%p] %q%u@%d ' -c log_directory='/var/log/postgresql' -c log_truncate_on_rotation=off -c log_rotation_age=1d
    links:
      - tfr

  tfr:
    build: TFR
    restart: unless-stopped
    volumes:
      - ./TFR/storage/migrations:/data/migrations
      - ./TFR/storage/uploads:/data/uploads
      - ./TFR/storage/logs:/data/logs
    environment:
      FLASK_KEY: ${THE_FRONT_ROOMS_SECRETE_KEY}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
