version: "3.8"

services:
  highscores:
    build: ./Highscore-Server/
    # restart: unless-stopped
    ports:
      - "5000:5000"
  caddy:
    image: caddy:latest
    # restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      - ACME_AGREE=true
      - TZ=Europe/London