version: "3.9"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
    #  - 80:80
      - 443:443
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      DOMAIN: expo.leggy.dev
    links:
      - highscore

  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
    links:
      - highscore

  highscore:
    build: ./Highscore-Server
    restart: unless-stopped
    volumes:
      - ./Highscore-Server/data:/data/storage
      - ./Highscore-Server/logs:/data/logs
    environment:
      FLASK_KEY: secret
      BEARER_TOKEN: 1234
      DB_USER: pguser
      DB_PASSWORD: secret
      DB_HOST: db
      DB_NAME: database
