version: "3.9"
services:
  caddy:
    hostname: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./Caddy/data:/data
      - ./Caddy/config:/config
    environment:
      - ACME_AGREE=true
      - TZ=Europe/London
  highscores:
    hostname: highscores
    build: ./Highscore-Server/
    ports:
      - "5000:5000"